import type { Metadata } from "next";

import "./globals.css";
import { Footer } from "@/components/ui/Footer";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Sk - MC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className="min-h-screen overflow-x-hidden text-customWhite">
        <AuthProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
